/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.footballtournament;

import cat.uvic.teknos.footballtournament.teams.*;
import cat.uvic.teknos.footballtournament.tournaments.Schedule;
import cat.uvic.teknos.footballtournament.tournaments.Tournament;

import java.time.Duration;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Comparator;;

public class App {
    public static void main(String[] args) {
        Tournament tournament = new Tournament();
        Schedule schedule = new Schedule();

        tournament.setSchedule(schedule);
        tournament.setParticipants(
                new TeamPSG(),
                new TeamArgentina(),
                new TeamBetis(),
                new TeamGironaFC()
        );
        tournament.setStartsOn(LocalDate.now());
        tournament.setEndsOn(LocalDate.now().plus(Duration.ofHours(5)));
        tournament.setName("World tournament");

        tournament.printDescription();
    }

    private static void printTournamentStatistics(Tournament tournament) {
        Arrays.stream(tournament.getParticipants())
            .sorted(Comparator.comparingInt(Team::getPoints))
            .forEach(Team::printStatistics);
    }
}
