/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.footballtournament;

import cat.uvic.teknos.footballtournament.emulators.TournamentEmulator;
import cat.uvic.teknos.footballtournament.teams.*;
import cat.uvic.teknos.footballtournament.tournaments.Match;
import cat.uvic.teknos.footballtournament.tournaments.Round;
import cat.uvic.teknos.footballtournament.tournaments.Schedule;
import cat.uvic.teknos.footballtournament.tournaments.Tournament;

import java.time.Duration;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Comparator;;

public class App {
    public static void main(String[] args) {
        Tournament tournament = new Tournament();
        Schedule schedule = new Schedule();

        TeamPSG psg = new TeamPSG();
        TeamArgentina arg = new TeamArgentina();
        TeamBetis bet = new TeamBetis();
        TeamGironaFC gir = new TeamGironaFC();

        Round round = new Round();
        for (int i = 0; i < 24; i++) {
            round.addMatch(new Match(
                    i % 2 == 0 ? psg : arg,
                    i % 2 == 0 ? bet : gir,
                    LocalDate.now().plusDays(i)
                    ));
        }
        schedule.addRound(round);

        tournament.setSchedule(schedule);
        tournament.setParticipants(psg, arg, bet, gir);
        tournament.setStartsOn(LocalDate.now());
        tournament.setEndsOn(LocalDate.now().plus(Duration.ofDays(365)));
        tournament.setName("World tournament");

        tournament.printDescription();

        TournamentEmulator.play(tournament);
        printTournamentStatistics(tournament);
        
    }

    private static void printTournamentStatistics(Tournament tournament) {
        Arrays.stream(tournament.getParticipants())
            .sorted(Comparator.comparingInt(Team::getPoints))
            .forEach(Team::printStatistics);
    }
}
